# Generated by Django 5.0.1 on 2024-01-31 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0002_alter_thread_options_thread_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated']},
        ),
    ]
